version: "3"
services:
        car-project:
                build: .
                ports:
                        - 80:8080
                volumes:
                        - ./src:/home/node/app
                user: node
                working_dir: /home/node/app
                command: bash -c "npm install && npm start"
